name = "cTab - Adjustable UI Positions"
prefix = "ctab_uip"
author = "[GRP9] Niklas Ky"
mainprefix = "z"

[files]
include = [
    "CHANGELOG.md",
    "ctab_uip_logo_ca.paa",
    "README.md",
    "keys/**",
    "LICENSE",
]

[version]
major = 1
minor = 0
patch = 2
git_hash = 0
